import { NativeEventEmitter, NativeModules } from 'react-native';

export interface AudioChunk {
  /** Absolute path for the WAV chunk generated by the Android service. */
  path: string;
  /** Millisecond timestamp when event was emitted. */
  timestamp: number;
}

export interface AudioLevelEvent {
  /** Normalized microphone level in the [0, 1] range. */
  level: number;
  /** Millisecond timestamp emitted from native side. */
  timestamp: number;
}

export interface AudioModuleConfig {
  /** Reserved for future custom sample-rate support. */
  sampleRate?: number;
  /** Reserved for future custom chunk-size support. */
  chunkDurationSeconds?: number;
}

export interface WhisperTranscriptEvent {
  chunkPath: string;
  text: string;
}

export interface WhisperTranscriptionErrorEvent {
  chunkPath: string;
  message: string;
}

export interface WhisperModelDownloadProgressEvent {
  bytesDownloaded: number;
  totalBytes: number | null;
  percent: number | null;
}

export interface WhisperBootstrapResult {
  path: string;
  downloaded: boolean;
  loaded: boolean;
}

export interface NativeAudioModule {
  startRecording(): void;
  stopRecording(): void;
  loadWhisperModel(modelPath: string): Promise<boolean>;
  downloadWhisperModel(modelUrl: string, fileName: string): Promise<string>;
  ensureWhisperModel(modelUrl: string, fileName: string): Promise<WhisperBootstrapResult>;
  unloadWhisperModel(): Promise<void>;
  isWhisperModelLoaded(): Promise<boolean>;
  transcribeChunk(chunkPath: string): Promise<string>;
  loadTranscriptionState(): Promise<string>;
  saveTranscriptionState(stateJson: string): Promise<void>;
}

type NativeAudioModuleRuntime = NativeAudioModule & {
  addListener(eventName: string): void;
  removeListeners(count: number): void;
};

const LINKING_ERROR =
  "The package 'NativeAudioModule' doesn't seem to be linked. Make sure:\n" +
  '- You rebuilt the app after installing native changes\n' +
  '- You are not using Expo Go\n';

let nativeAudioEventEmitter: NativeEventEmitter | null = null;

const getNativeAudioModule = (): NativeAudioModuleRuntime => {
  const module = NativeModules.NativeAudioModule as NativeAudioModuleRuntime | undefined;
  if (!module) {
    throw new Error(LINKING_ERROR);
  }
  return module;
};

const getNativeAudioEventEmitter = (): NativeEventEmitter => {
  if (nativeAudioEventEmitter == null) {
    nativeAudioEventEmitter = new NativeEventEmitter(getNativeAudioModule());
  }
  return nativeAudioEventEmitter;
};

export const VoiceScribeAudio = {
  startRecording(): void {
    getNativeAudioModule().startRecording();
  },

  stopRecording(): void {
    getNativeAudioModule().stopRecording();
  },

  async loadWhisperModel(modelPath: string): Promise<boolean> {
    return getNativeAudioModule().loadWhisperModel(modelPath);
  },

  async downloadWhisperModel(modelUrl: string, fileName: string): Promise<string> {
    return getNativeAudioModule().downloadWhisperModel(modelUrl, fileName);
  },

  async ensureWhisperModel(
    modelUrl: string,
    fileName: string,
  ): Promise<WhisperBootstrapResult> {
    return getNativeAudioModule().ensureWhisperModel(modelUrl, fileName);
  },

  async unloadWhisperModel(): Promise<void> {
    await getNativeAudioModule().unloadWhisperModel();
  },

  async isWhisperModelLoaded(): Promise<boolean> {
    return getNativeAudioModule().isWhisperModelLoaded();
  },

  async transcribeChunk(chunkPath: string): Promise<string> {
    return getNativeAudioModule().transcribeChunk(chunkPath);
  },

  async loadTranscriptionState(): Promise<string> {
    return getNativeAudioModule().loadTranscriptionState();
  },

  async saveTranscriptionState(stateJson: string): Promise<void> {
    await getNativeAudioModule().saveTranscriptionState(stateJson);
  },

  /**
   * Receive chunk file path events emitted by Android foreground service.
   */
  onChunkReady(callback: (chunk: AudioChunk) => void) {
    return getNativeAudioEventEmitter().addListener('onAudioChunkReady', (path: string) => {
      callback({ path, timestamp: Date.now() });
    });
  },

  /**
   * Receive on-device whisper transcription events from native layer.
   */
  onTranscriptReady(callback: (event: WhisperTranscriptEvent) => void) {
    return getNativeAudioEventEmitter().addListener('onTranscriptReady', callback);
  },

  /**
   * Receive normalized microphone level updates from native recorder loop.
   */
  onAudioLevel(callback: (event: AudioLevelEvent) => void) {
    return getNativeAudioEventEmitter().addListener('onAudioLevel', callback);
  },

  /**
   * Receive transcription error events emitted by native layer.
   */
  onTranscriptionError(callback: (event: WhisperTranscriptionErrorEvent) => void) {
    return getNativeAudioEventEmitter().addListener('onTranscriptionError', callback);
  },

  /**
   * Receive whisper model download progress during bootstrap.
   */
  onModelDownloadProgress(callback: (event: WhisperModelDownloadProgressEvent) => void) {
    return getNativeAudioEventEmitter().addListener('onModelDownloadProgress', callback);
  },
};
